name: emily
description: Emily's CLI assistant eases the chore of developing apps on Flutter.
version: 0.1.0
repository: https://github.com/MrBIOSs/emily-cli

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.2

dependencies:
  mason_logger: ^0.3.3
  args: ^2.5.0
  dcli: ^7.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  emily: emily